
Vagrant.configure(2) do |config|

  config.vm.box = "hashicorp/precise64"

  VAGRANT_JSON = JSON.parse(Pathname(__FILE__).dirname.join('nodes', 'vagrant.json').read)

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = "roles"
    chef.data_bags_path = "data_bags"
    chef.provisioning_path = "/tmp/vagrant-chef"    
    chef.run_list = VAGRANT_JSON.delete('run_list')
    chef.json = VAGRANT_JSON
  end

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "haproxy"
  end
  
  config.vm.network "private_network", ip: "192.168.33.2"
  config.vm.hostname = "Awesome-Loadbalancer"
  config.vm.post_up_message = "Your Loadbalancer box is up and operational using Static IP 192.168.33.2"

end
